# Generated by Django 5.0.3 on 2024-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('due_date', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('HOUSE', 'Housing'), ('TRANS', 'Transportation'), ('UTL', 'Utilities'), ('INS', 'Insurance'), ('MED', 'Medical'), ('SID', 'Savings investment & debt'), ('ENT', 'Entertainment'), ('MISC', 'Miscellaneous')], max_length=7)),
                ('frequency', models.CharField(choices=[('MON', 'Monthly'), ('BW', 'biweekly'), ('SM', 'Semimonthly'), ('W', 'Weekly'), ('AN', 'Annually')], max_length=3)),
            ],
        ),
    ]
