# Generated by Django 5.0.3 on 2024-04-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='frequency',
            field=models.CharField(choices=[('MON', 'Monthly'), ('BW', 'Bi-weekly'), ('SM', 'Semimonthly'), ('W', 'Weekly'), ('AN', 'Annually')], max_length=3),
        ),
    ]
