# Generated by Django 5.0.3 on 2024-04-08 23:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='id',
        ),
        migrations.AlterField(
            model_name='income',
            name='pay_date_two',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(28), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
