# Generated by Django 5.0.3 on 2024-04-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_income_id_alter_income_pay_date_two_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='frequncy',
            new_name='frequency',
        ),
    ]
